config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]

  resource :user, only: [:create, :new]

    root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:current_user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = 'You entered wrong password or email'
      render 'new'
    end
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end

  def chek_authenticate
    return if signed_in?
    redirect_to new_session_path
  end

  private

  def current_user
    User.find(session[:current_user_id])
  end

  def signed_in?
    return true if session[:current_user_id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params.require(:user).permit!)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def new
    @user = User.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < SessionsController
  before_action :chek_authenticate

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_signed_in?
    return true if session[:current_user_id]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekhub</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= link_to 'Log out', session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user, url: user_path do |f| %>
  <p>
  <%= f.label :email %>
  <br>
  <%= f.text_field :email %>
  <%= @user.errors[:email].first %>
</p>
<p>
  <%= f.label :password %>
  <br>
  <%= f.password_field :password %>
  <%= @user.errors[:password].first %>
</p>
<p>
  <%= f.label :password_confirmation%>
  <br>
  <%= f.password_field :password_confirmation %>
  <%= @user.errors[:password_confirmation].first %>
</p>
  <%= f.submit :OK %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>